services:
  gigablog_db:
    image: postgres:17.2-bullseye
    container_name: gigablog_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5431:5432"
    networks:
      - gigablog-network

  gigablog_pgadmin:
    image: dpage/pgadmin4:9.1
    container_name: gigablog_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5051:80"
    networks:
      - gigablog-network

  # gigablog_backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: gigablog_backend
  #   restart: unless-stopped
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://gigablog_db:5432/${POSTGRES_DB}
  #     - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
  #     - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=none
  #     - SPRING_FLYWAY_ENABLED=true
  #   depends_on:
  #     - gigablog_db
  #   networks:
  #     - gigablog-network

networks:
  gigablog-network:
    driver: bridge