spring:
    application:
        name: GigaBlog Backend

    datasource:
       url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5431/${POSTGRES_DB}
       username: ${POSTGRES_USER}
       password: ${POSTGRES_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update

    flyway:
        enabled: true
        validate-on-migrate: false