apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigablog-app-deployment
  namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gigablog-app
  template:
    metadata:
      labels:
        app: gigablog-app
    spec:
      containers:wc
        - name: gigablog-app-container
          image: cybergigzz/gigablog
          ports:
            - containerPort: 8080
          env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres-service:5432/gigablog_db
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres-credentials  
                key: username             
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials  
                key: password