apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: gigablog-db  
          image: postgres:17.2-bullseye  
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: POSTGRES_DB
              value: postgres_gigablog
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/gigablog_db"
          ports:
            - containerPort: 5432 
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          emptyDir: {}

