apiVersion: apps/v1
kind: Deployment
metadata:
  name: gigablog-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gigablog-app
  template:
    metadata:
      labels:
        app: gigablog-app
    spec:
      containers:
        - name: gigablog-app-container
          image: your-dockerhub-username/gigablog:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service:5432/gigablog_db
            - name: SPRING_DATASOURCE_USERNAME
              value: gigablog_user
            - name: SPRING_DATASOURCE_PASSWORD
              value: secure_password