spring:
  datasource:
    url: jdbc:tc:postgresql:17:///testdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: testuser
    password: testpass
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    locations: classpath:db/migration