spring:
  datasource:
    url: jdbc:tc:postgresql:16:///testdb?TC_TMPFS=/testtmpfs:rw
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none # Let Flyway handle schema
  flyway:
    enabled: true
    locations: classpath:db/migration